### ISSUE TITLE
CFLAG Compiling error

### ISSUE THREAD

**Issue by Harv234** [mciobanu/mp3diags#4]
MP3Diags (unstable) does not compile on archlinux because of the standard compiler flags.
The make process throws the following error:
Mp3TransformThread.cpp:679:15: error: format not a string literal and no format arguments [-Werror=format-security]
Temporarily disabling this in CFLAGS fixes the error and the program compiles again. Seems there is a format error in Mp3TransformThread.cpp but it is beyond my scope to find out where...

**Comment by mciobanu** [comment]
Can you post more details about how you got this?

I just installed a new Arch Linux VM (which was a significant pain, but that's another story) with _GCC 11.1.0_, cloned the repo and got no error when running _Build.sh_ (after installing the dependencies).

**Comment by Harv234** [comment]
Well, that's not the way to build the package in Archlinux. Mp3diags-unstable has an entry in AUR: (https://aur.archlinux.org/packages/mp3diags-unstable/) where you can download the PKGBUILD for building the program. Only when building it the arch way using makepkg it takes into account /etc/makepkg.conf and this file defines  -Werror=format-security as a makeflag for gcc causing the build to fail...

Ensure the base-devel package group is installed in full (pacman -S --needed base-devel) then goto to the directoy where you unpacked the mp3diags-unstable snapshot (https://aur.archlinux.org/cgit/aur.git/snapshot/mp3diags-unstable.tar.gz) and try to build it with makepg -cfs ...

**Comment by mciobanu** [comment]
OK, I made some changes and [pushed them](https://github.com/mciobanu/mp3diags/commit/efc264681d133562ce282a244cb5b32574b26bb5?branch=efc264681d133562ce282a244cb5b32574b26bb5&diff=split) but I guess for this thing to work you'd need a new release, like "1.5.02" to be created at SourceForge, right?

**Comment by Harv234** [comment]
No, not necessarily. I can change the source to the mentioned commit and push a new Package release version without changing MP3Diag-unstable's  release tag. Just like you prefer. I just adapted my PKGBUILD and can confirm it works again. As I am the archlinux AUR maintainer of the package I can make the change any way you like it. 

BTW, I just stumbled over one small glitch. The MP3Diags.desktop file is not reflecting the 'unstable' branch. I can work around this by renaming and editing it:
	mv "desktop/MP3Diags.desktop" "desktop/MP3Diags-unstable.desktop"
	sed -i 's|MP3Diags|MP3Diags-unstable|g' "desktop/MP3Diags-unstable.desktop"

Just tell me how you want me to do it.

**Comment by mciobanu** [comment]
Not sure I get the renaming part. If you're talking about what is in https://github.com/mciobanu/mp3diags/tree/master/desktop - yes, it doesn't have the right name, but the version at https://sourceforge.net/projects/mp3diags/files/unstable/mp3diags-src/ has MP3Diags-unstable.desktop. And it also has some changes in Helpers.cpp, SessionEditorDlgImpl.cpp, and Version.cpp. Those changes are made when running MakeArchives.sh, which is what I do when I create an official new release. Those changes set the correct version in several places. (Pretty cumbersome, but not annoying enough to make me redesign this thing.)

Anyway, I found a much more annoying issue, namely that with the latest Plasma on OpenSuse Tumbleweed it is no longer possible to close the program, so I need a fix and a new release for this, regardless of Arch status.

All in all, I think it's better to wait for this new release, and in the meantime have some hack to make the thing compile. I guess either drop -Werror=format-security if possible, or create a patch and apply it after downloading from SourceForge.

**Comment by Harv234** [comment]
Ok, I'll wait for the new release then. For now I will post a comment to the AUR package website how to disable -Werror=format-security in /etc/makepkg.conf. Thank you for your keeping MP3Diags alive!

**Comment by mciobanu** [comment]
https://sourceforge.net/projects/mp3diags/files/unstable/mp3diags-src/ has 1.5.02 with all these things supposedly fixed, but please let me know if there are remaining issues.

**Comment by Harv234** [comment]
Just pushed the new version to the AUR. Builds fine without any errors. Good work!
